title: Mingrui Li's Homepage
page-top-title: Mingrui Li
top-section-bg-text: Read widely, absorb carefully, amass deeply, share gradually.
home-subtitle: Mingrui Li&ensp;|&ensp;李明睿
copyright-text: '&copy; Mingrui 2025. All Rights Reserved.'
