title: Mingrui Li's Homepage
page-top-title: Mingrui Li
top-section-bg-text: Read widely, absorb carefully, amass deeply, share gradually.
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Mingrui 2025. All Rights Reserved.'
